### ISSUE TITLE
kejiwanjia一直处于已经签到状态

### ISSUE THREAD

**Issue by Marb13** [Mr-Liu1996/ql_script#5]
辛苦作者了

**Comment by Mr-Liu1996** [comment]
已经签到代表签到过了，为了签到成功，设置了每6个小时运行一次

**Comment by lichtquant** [comment]
好像是需要自己打开网站任务列表激活一次，不然每6小时运行一次也只会显示昨日的签到得分并显示已经签到

**Comment by Mr-Liu1996** [comment]
网站应该有个签到触发机制，签到过后隔一定小时才能签到，而不是没日0点0分都可以签到

**Comment by Marb13** [comment]
好的，感谢作者，我修改下定时时间再看下，主要是自动签到不奏效，自己登陆网站激活后再执行脚本就可以签到，所以很困惑
